/**
 * Generator for the runtime creature-spec-verification include (`inc_spec_check`
 * by default).
 *
 * Every `verify_*` tool in this project checks static GFF data — it can prove a
 * blueprint has the right *fields* set, never that the engine actually behaves
 * as intended once a real server loads the module. This closes that gap for
 * creatures: `SPEC_VerifyCreature()` compares a creature's actual runtime race,
 * appearance, class, level, package, feats and spells against `SPEC_*` local
 * variables set on its blueprint at creation time, and logs one grep-able
 * `[SPEC_OK]`/`[SPEC_FAIL]` line per creature per check. See
 * docs/runtime-verification-spec.md for the full design and open questions.
 *
 * The whole thing is a no-op unless `MCP_VERIFY_MODE` is set on the module —
 * dev-time instrumentation, not a player-facing feature.
 */

/** Racial-feat and class-feat lookup tables, keyed by nwscript.nss constant value. */
export interface SpecCheckOptions {
  /** Include resref to write, so the usage comment names the real file. */
  includeName?: string;
}

/**
 * Representative racial feat per `racialtypes.2da` row 0-6 — verified against
 * the real `race_feat_<race>.2da` tables (row 0 of each) via `resolve_2da`.
 * `null` means "not checked."
 */
export const RACIAL_FEATS: Record<number, { id: number; label: string } | null> = {
  0: { id: 228, label: "DARKVISION" }, // Dwarf
  1: { id: 235, label: "IMMUNITYSLEEP" }, // Elf
  2: { id: 170, label: "SPELLFOCUSILL" }, // Gnome
  3: { id: 247, label: "SKILLAFFINITYMOVESI" }, // Halfling
  4: { id: 235, label: "IMMUNITYSLEEP" }, // Half-Elf
  5: { id: 228, label: "DARKVISION" }, // Half-Orc
  6: { id: 258, label: "QUICKMASTER" }, // Human
};

/**
 * Representative class feat: an automatically-granted (`List=3`), level-1
 * (`GrantedOnLevel=1`) feat from the real `cls_feat_<class>.2da` tables,
 * verified via `search_2da(column: "GrantedOnLevel", value: "1")`.
 *
 */
export const CLASS_FEATS: Record<number, { id: number; label: string } | null> = {
  0: { id: 194, label: "BARBENDURANCE" }, // Barbarian
  1: { id: 197, label: "BARDICKNOWLEDGE" }, // Bard
  2: { id: 294, label: "TURNUNDEAD" }, // Cleric
  3: { id: 48, label: "WEAPPROFDRUID" }, // Druid
  4: { id: 45, label: "WEAPPROFMAR" }, // Fighter
  5: { id: 49, label: "WEAPPROFMONK" }, // Monk
  6: { id: 217, label: "DIVINEGRACE" }, // Paladin
  7: { id: 201, label: "TRACKLESSSTEP" }, // Ranger
  8: { id: 50, label: "WEAPPROFROGUE" }, // Rogue
  9: { id: 303, label: "FAMILIAR" }, // Sorcerer
  10: { id: 51, label: "WEAPPROFWIZARD" }, // Wizard
};

const RACE_NAMES: Record<number, string> = {
  0: "Dwarf",
  1: "Elf",
  2: "Gnome",
  3: "Halfling",
  4: "Half-Elf",
  5: "Half-Orc",
  6: "Human",
};

const CLASS_CONSTANTS: Record<number, string> = {
  0: "CLASS_TYPE_BARBARIAN",
  1: "CLASS_TYPE_BARD",
  2: "CLASS_TYPE_CLERIC",
  3: "CLASS_TYPE_DRUID",
  4: "CLASS_TYPE_FIGHTER",
  5: "CLASS_TYPE_MONK",
  6: "CLASS_TYPE_PALADIN",
  7: "CLASS_TYPE_RANGER",
  8: "CLASS_TYPE_ROGUE",
  9: "CLASS_TYPE_SORCERER",
  10: "CLASS_TYPE_WIZARD",
};

function racialFeatBranches(): string {
  return Object.entries(RACIAL_FEATS)
    .map(([race, feat]) => {
      const name = RACE_NAMES[Number(race)];
      if (!feat) return `    if (nRace == ${race}) return -1; // ${name} — not checked`;
      return `    if (nRace == ${race}) return ${feat.id}; // ${name} — ${feat.label}`;
    })
    .join("\n");
}

function classFeatBranches(): string {
  return Object.entries(CLASS_FEATS)
    .map(([classId, feat]) => {
      const constant = CLASS_CONSTANTS[Number(classId)];
      if (!feat) return `    if (nClass == ${constant}) return -1; // UNCONFIRMED — see comment above`;
      return `    if (nClass == ${constant}) return ${feat.id}; // ${feat.label}`;
    })
    .join("\n");
}

/** Generate the full NWScript source for the spec-check include. */
export function generateSpecCheckInclude(opts: SpecCheckOptions = {}): string {
  const includeName = opts.includeName ?? "inc_spec_check";

  return `// Runtime creature spec verification.
//
// GENERATED by nwn-mcp create_spec_verification — do not hand-edit. Rerun the
// tool to regenerate; hand edits are lost and, worse, silently diverge from
// what the SPEC_* varTable data on each blueprint expects.
//
// Compares a creature's *actual* runtime race/appearance/class/level/package/
// feats/spells against SPEC_* local variables set on its blueprint at creation
// time (create_creature_blueprint's varTable param — no extra tooling needed to
// write the spec, only to check it). Static verify_creature can only prove the
// GFF fields look right; this proves what LevelUpHenchman() (or any other
// runtime leveling call) actually did once a real server has loaded the module.
// See docs/runtime-verification-spec.md for the full design.
//
// Gated by MCP_VERIFY_MODE, a MODULE LOCAL VARIABLE (module.ifo has no
// VarTable to bake a static flag into, unlike UTC/UTP blueprints). a_mod_load
// sets it with SetLocalInt(GetModule(), "MCP_VERIFY_MODE", 1); flip that
// literal to 0 as the last build step before delivering the module — every
// call below goes through this one function, so no individual caller needs
// its own gate.
//
// SPEC_* schema — write all of these together via varTable, or omit all of
// them (the SPEC_ENABLED check makes "no spec on this creature" the same as
// "not checked", not a fail):
//   SPEC_ENABLED     int  1                 -- presence marker; required
//   SPEC_RACE        int  racialtypes.2da row
//   SPEC_APPEARANCE  int  appearance.2da row (same value as SPEC_RACE for the
//                                              7 standard PC races)
//   SPEC_CLASS       int  expected primary class ID
//   SPEC_LEVEL       int  expected GetLevelByClass(SPEC_CLASS, ...) / hit dice
//   SPEC_PACKAGE     int  expected StartingPackage (normally = SPEC_CLASS)
//
// Usage from any script that spawns or levels a creature:
//
//     #include "${includeName}"
//     void main()
//     {
//         SPEC_VerifyCreature(OBJECT_SELF);
//     }
//
// Call SPEC_VerifyCreature(oCreature) from OnSpawn (baseline, for creatures
// leveled statically at build time) AND immediately after any script call that
// changes ClassList — LevelUpHenchman() at recruit, and any future quest/
// retrain script that levels an NPC mid-story. There is no "already ran"
// guard: a creature checked after two separate level-ups logs twice, which is
// expected and correct, not a duplicate to suppress.
//
// SPEC_SelfTestOnSpawn(oCreature) is the headless variant: it levels oCreature
// up to its own SPEC_LEVEL (if it isn't already there) and then calls
// SPEC_VerifyCreature() — for testing without a real PC ever connecting to
// recruit a companion through its dialog. Safe precedent: BioWare's own stock
// x0_ch_hen_spawn.nss calls LevelUpHenchman() straight from OnSpawn on an
// unrecruited companion in shipped content. Don't replace a companion's
// ScriptSpawn with this outright — chain it after the stock
// x0_ch_hen_spawn call instead, so the associate-AI setup that script also
// does isn't lost.
//
// Log protocol (grep the server log for these after a headless run):
//   [SPEC_OK] tag=<tag>
//   [SPEC_FAIL] tag=<tag> field=<race|appearance|racial_feat|level|hit_dice|package|class_feat|spell_count> expected=<x> actual=<y>

int MCP_SPEC_ENABLED_FLAG = 1;

// Representative racial feat per racialtypes.2da row 0-6 — verified against the
// real race_feat_<race>.2da tables (row 0 of each). -1 = not checked.
int SpecExpectedRacialFeat(int nRace)
{
${racialFeatBranches()}
    return -1;
}

// Representative class feat: an automatically-granted (List=3), level-1
// (GrantedOnLevel=1) feat from the real cls_feat_<class>.2da tables. -1 = not
// checked.
int SpecExpectedClassFeat(int nClass)
{
${classFeatBranches()}
    return -1;
}

// Classes whose spell_count is checkable via GetKnownSpellCount() at all.
// Cleric/Druid/Paladin/Ranger are "prepared, cast from the full class list"
// divine casters -- they have no personal "known spells" list the way
// Bard/Sorcerer/Wizard do, so GetKnownSpellCount() structurally returns 0 for
// them regardless of how correctly built they are. Verified via a live
// end-to-end run: 100% of Cleric/Druid/Paladin/Ranger test creatures failed
// this check even after a real, successful LevelUpHenchman() pass, while
// every Bard/Sorcerer/Wizard above level 1 passed cleanly. Checking a
// prepared caster's actual state would need GetIsSpellPrepared-family
// functions, not GetKnownSpellCount -- out of scope here; skip the check
// entirely for these four rather than produce a guaranteed false positive.
//
// Sorcerer/Wizard cast from level 1; Bard's first spells come at class level
// 2, matching NWN's own ruleset (verified: a level-1 Bard test creature had
// zero known spells while level 2+ Bards did not).
int SpecIsCasterAtLevel(int nClass, int nLevel)
{
    if (nClass == CLASS_TYPE_SORCERER || nClass == CLASS_TYPE_WIZARD)
        return nLevel >= 1;
    if (nClass == CLASS_TYPE_BARD)
        return nLevel >= 2;
    return FALSE;
}

// Sum of known/memorized spells across every spell level, 0 (cantrips/orisons)
// through 9.
int SpecCountSpells(object oCreature, int nClass)
{
    int nCount = 0;
    int nLevel;
    for (nLevel = 0; nLevel <= 9; nLevel++)
        nCount += GetKnownSpellCount(oCreature, nClass, nLevel);
    return nCount;
}

void SpecLogFail(string sTag, string sField, int nExpected, int nActual)
{
    WriteTimestampedLogEntry("[SPEC_FAIL] tag=" + sTag + " field=" + sField +
        " expected=" + IntToString(nExpected) + " actual=" + IntToString(nActual));
}

// Compare oCreature's actual runtime state against its SPEC_* local variables
// and log one [SPEC_OK] (all checks passed) or one [SPEC_FAIL] line per failed
// field. No-op unless MCP_VERIFY_MODE is set on the module, and unless this
// specific creature carries SPEC_ENABLED == 1.
void SPEC_VerifyCreature(object oCreature)
{
    if (!GetLocalInt(GetModule(), "MCP_VERIFY_MODE")) return;
    if (!GetIsObjectValid(oCreature)) return;
    if (GetLocalInt(oCreature, "SPEC_ENABLED") != MCP_SPEC_ENABLED_FLAG) return;

    string sTag = GetTag(oCreature);
    int bPass = TRUE;

    int nExpectRace = GetLocalInt(oCreature, "SPEC_RACE");
    int nActualRace = GetRacialType(oCreature);
    if (nActualRace != nExpectRace)
    {
        bPass = FALSE;
        SpecLogFail(sTag, "race", nExpectRace, nActualRace);
    }

    int nExpectAppearance = GetLocalInt(oCreature, "SPEC_APPEARANCE");
    int nActualAppearance = GetAppearanceType(oCreature);
    if (nActualAppearance != nExpectAppearance)
    {
        bPass = FALSE;
        SpecLogFail(sTag, "appearance", nExpectAppearance, nActualAppearance);
    }

    int nRacialFeat = SpecExpectedRacialFeat(nExpectRace);
    if (nRacialFeat != -1 && !GetHasFeat(nRacialFeat, oCreature))
    {
        bPass = FALSE;
        SpecLogFail(sTag, "racial_feat", nRacialFeat, -1);
    }

    int nExpectClass = GetLocalInt(oCreature, "SPEC_CLASS");
    int nExpectLevel = GetLocalInt(oCreature, "SPEC_LEVEL");
    int nActualLevel = GetLevelByClass(nExpectClass, oCreature);
    if (nActualLevel != nExpectLevel)
    {
        bPass = FALSE;
        SpecLogFail(sTag, "level", nExpectLevel, nActualLevel);
    }

    int nHD = GetHitDice(oCreature);
    if (nHD != nExpectLevel)
    {
        bPass = FALSE;
        SpecLogFail(sTag, "hit_dice", nExpectLevel, nHD);
    }

    int nExpectPackage = GetLocalInt(oCreature, "SPEC_PACKAGE");
    int nActualPackage = GetCreatureStartingPackage(oCreature);
    if (nActualPackage != nExpectPackage)
    {
        bPass = FALSE;
        SpecLogFail(sTag, "package", nExpectPackage, nActualPackage);
    }

    int nClassFeat = SpecExpectedClassFeat(nExpectClass);
    if (nClassFeat != -1 && !GetHasFeat(nClassFeat, oCreature))
    {
        bPass = FALSE;
        SpecLogFail(sTag, "class_feat", nClassFeat, -1);
    }

    if (SpecIsCasterAtLevel(nExpectClass, nExpectLevel))
    {
        int nSpellCount = SpecCountSpells(oCreature, nExpectClass);
        if (nSpellCount == 0)
        {
            bPass = FALSE;
            SpecLogFail(sTag, "spell_count", 1, 0);
        }
    }

    if (bPass) WriteTimestampedLogEntry("[SPEC_OK] tag=" + sTag);
}

// Headless self-test: level oCreature up to its own SPEC_LEVEL and immediately
// verify it, without needing a real PC to connect and click through a recruit
// dialog. Safe precedent for calling LevelUpHenchman() straight from OnSpawn,
// on an unrecruited companion: BioWare's own stock x0_ch_hen_spawn.nss does
// exactly this (loops LevelUpHenchman() 13 times to pre-level a companion in
// the Undermountain starting room) in shipped, official content — this
// generalizes that same pattern to any SPEC_ENABLED creature, gated so it only
// ever runs during nwn-mcp's own verification pass.
//
// The level-up loop only runs while the creature is still under its target
// level, so calling this more than once (a creature can spawn more than once
// per module run, or already be leveled via a real recruit) is always safe —
// a creature already at or above SPEC_LEVEL just goes straight to the verify
// call with no further leveling.
//
// For a companion, do NOT replace ScriptSpawn with this outright — that would
// drop the stock x0_ch_hen_spawn associate-AI setup (SetAssociateListenPatterns,
// etc.). Chain instead: a wrapper OnSpawn script calls
// ExecuteScript("x0_ch_hen_spawn", OBJECT_SELF) first, then this.
void SPEC_SelfTestOnSpawn(object oCreature)
{
    if (!GetLocalInt(GetModule(), "MCP_VERIFY_MODE")) return;
    if (!GetIsObjectValid(oCreature)) return;
    if (GetLocalInt(oCreature, "SPEC_ENABLED") != MCP_SPEC_ENABLED_FLAG) return;

    int nExpectClass = GetLocalInt(oCreature, "SPEC_CLASS");
    int nExpectLevel = GetLocalInt(oCreature, "SPEC_LEVEL");
    int nGuard = 0;
    while (GetLevelByClass(nExpectClass, oCreature) < nExpectLevel && nGuard < 40)
    {
        LevelUpHenchman(oCreature, CLASS_TYPE_INVALID, TRUE, PACKAGE_INVALID);
        nGuard++;
    }

    SPEC_VerifyCreature(oCreature);
}
`;
}
