import { describe, expect, it } from "vitest";
import { generateSystestLogInclude } from "./systest-log-script.js";

describe("generateSystestLogInclude", () => {
  it("gates both exported functions behind MCP_VERIFY_MODE", () => {
    const source = generateSystestLogInclude();
    const functions = source.split(/^void SYSTEST_/m).slice(1);
    expect(functions.length).toBeGreaterThanOrEqual(2);
    for (const fn of functions) {
      expect(fn).toContain('if (!GetLocalInt(GetModule(), "MCP_VERIFY_MODE")) return;');
    }
  });

  it("emits the exact [SYSTEST_DAMAGE] log line format", () => {
    const source = generateSystestLogInclude();
    expect(source).toContain('"[SYSTEST_DAMAGE] target=" + sTarget');
    expect(source).toContain('" attacker=" + sAttacker + " amount=" + IntToString(nAmount)');
  });

  it("emits the exact [SYSTEST_DEATH] log line format", () => {
    const source = generateSystestLogInclude();
    expect(source).toContain('"[SYSTEST_DEATH] tag=" + sTag + " killer=" + sKiller');
  });

  it("declares SYSTEST_LogDamage and SYSTEST_LogDeath with the documented single-arg signature", () => {
    const source = generateSystestLogInclude();
    expect(source).toContain("void SYSTEST_LogDamage(object oCreature)");
    expect(source).toContain("void SYSTEST_LogDeath(object oCreature)");
  });

  it("reads damage/attacker/killer from the engine's own event context, never from GetPCSpeaker", () => {
    // Regression guard: ExecuteScript() doesn't forward custom arguments to a
    // chained wrapper, so these functions must read event data via the
    // engine's own context functions (GetLastDamager/GetTotalDamageDealt/
    // GetLastHostileActor) rather than assuming a PC speaker exists — NPC-NPC
    // scenarios have no PC involved at all.
    const source = generateSystestLogInclude();
    expect(source).toContain("GetLastDamager(oCreature)");
    expect(source).toContain("GetTotalDamageDealt()");
    expect(source).toContain("GetLastHostileActor(oCreature)");
    expect(source).not.toContain("GetPCSpeaker");
  });

  it("validates object handles before reading their tag", () => {
    const source = generateSystestLogInclude();
    expect(source).toContain("GetIsObjectValid(oAttacker)");
    expect(source).toContain("GetIsObjectValid(oKiller)");
    expect(source).toContain("GetIsObjectValid(oCreature)");
  });

  it("uses the default include name inc_systest_log in the usage comment", () => {
    const source = generateSystestLogInclude();
    expect(source).toContain('#include "inc_systest_log"');
  });

  it("honors a custom includeName in the usage comment", () => {
    const source = generateSystestLogInclude({ includeName: "my_systest" });
    expect(source).toContain('#include "my_systest"');
    expect(source).not.toContain('#include "inc_systest_log"');
  });

  it("marks the file as generated, not hand-editable", () => {
    const source = generateSystestLogInclude();
    expect(source).toMatch(/GENERATED by nwn-mcp create_systest_instrumentation/);
  });
});
