/**
 * Generator for the systems-test logging include (`inc_systest_log` by
 * default).
 *
 * The `systest-module` skill builds a small, disposable module purpose-built
 * to exercise this project's own systems (opposed-faction combat, caster
 * fixtures, regression fixtures for the six bug classes fixed in "The Salt
 * Gate Conspiracy") and run it through `run_live_verification` to watch real
 * engine behavior via grep-able log output. `inc_spec_check` already covers
 * creature stat/feat/spell correctness at spawn; this covers the two things
 * it doesn't — real combat outcomes and (in a later iteration) NPC-to-NPC
 * dialog — by chaining small logging hooks onto ScriptDamaged/ScriptDeath.
 *
 * Gated by MCP_VERIFY_MODE, the same module-local switch inc_spec_check.nss
 * already uses (module.ifo has no VarTable to bake a static flag into) — a
 * no-op in any module not built for nwn-mcp's own verification.
 */

export interface SystestLogOptions {
  /** Include resref to write, so the usage comment names the real file. */
  includeName?: string;
}

/** Generate the full NWScript source for the systest logging include. */
export function generateSystestLogInclude(opts: SystestLogOptions = {}): string {
  const includeName = opts.includeName ?? "inc_systest_log";

  return `// Runtime systems-test logging instrumentation.
//
// GENERATED by nwn-mcp create_systest_instrumentation — do not hand-edit.
// Rerun the tool to regenerate.
//
// Small, chainable logging helpers for the systest-module skill's combat
// fixtures — real combat outcomes are something inc_spec_check.nss cannot
// see (it only checks state at spawn), and static verify_* checks cannot
// see at all. Gated by MCP_VERIFY_MODE, a MODULE LOCAL VARIABLE (module.ifo
// has no VarTable to bake a static flag into, unlike UTC/UTP blueprints) —
// a_mod_load sets it with SetLocalInt(GetModule(), "MCP_VERIFY_MODE", 1);
// every call below is a no-op when it isn't set.
//
// Log protocol (grep the server log for these after a headless run):
//   [SYSTEST_DAMAGE] target=<tag> attacker=<tag> amount=<n>
//   [SYSTEST_DEATH] tag=<tag> killer=<tag>
//
// WIRING (chain, never replace — same convention create_random_abilities_system
// already established): write a small per-role wrapper script that calls
// ExecuteScript() on the creature's original ScriptDamaged/ScriptDeath first,
// then SYSTEST_LogDamage(OBJECT_SELF)/SYSTEST_LogDeath(OBJECT_SELF), and pass
// it via create_creature_blueprint's \`scripts\` param. ExecuteScript() does
// NOT forward custom arguments — a chained wrapper only keeps OBJECT_SELF, so
// these functions deliberately take just the creature and read the rest
// (damager, damage amount, killer) from the engine's own OnDamaged/OnDeath
// event context (GetLastDamager/GetTotalDamageDealt/GetLastHostileActor),
// exactly like the stock nw_c2_default6/nw_c2_default7 scripts do.
//
// Usage from a per-role wrapper script:
//
//     #include "${includeName}"
//     void main()
//     {
//         ExecuteScript("nw_c2_default6", OBJECT_SELF); // or the creature's own original
//         SYSTEST_LogDamage(OBJECT_SELF);
//     }

// Chain onto ScriptDamaged (fires from within the creature's own OnDamaged
// event, so GetLastDamager/GetTotalDamageDealt read the event that's
// currently in progress).
void SYSTEST_LogDamage(object oCreature)
{
    if (!GetLocalInt(GetModule(), "MCP_VERIFY_MODE")) return;
    if (!GetIsObjectValid(oCreature)) return;

    string sTarget = GetTag(oCreature);
    object oAttacker = GetLastDamager(oCreature);
    string sAttacker = GetIsObjectValid(oAttacker) ? GetTag(oAttacker) : "unknown";
    int nAmount = GetTotalDamageDealt();

    WriteTimestampedLogEntry("[SYSTEST_DAMAGE] target=" + sTarget +
        " attacker=" + sAttacker + " amount=" + IntToString(nAmount));
}

// Chain onto ScriptDeath.
void SYSTEST_LogDeath(object oCreature)
{
    if (!GetLocalInt(GetModule(), "MCP_VERIFY_MODE")) return;
    if (!GetIsObjectValid(oCreature)) return;

    string sTag = GetTag(oCreature);
    object oKiller = GetLastHostileActor(oCreature);
    string sKiller = GetIsObjectValid(oKiller) ? GetTag(oKiller) : "unknown";

    WriteTimestampedLogEntry("[SYSTEST_DEATH] tag=" + sTag + " killer=" + sKiller);
}
`;
}
